allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    def configureNamespace = { p ->
        if (p.extensions.findByName('android') != null) {
            if (p.android.namespace == null) {
                p.android.namespace = "com.example.quest." + p.name.replaceAll("[- ]", ".")
            }
        }
    }
    if (project.state.executed) {
        configureNamespace(project)
    } else {
        project.afterEvaluate { configureNamespace(it) }
    }
}


tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
